### ISSUE TITLE
关于数字签名

### ISSUE THREAD

**Issue by humor502** [BSG-75/RA3Bar-RA3Launcher#1]
你好，岚依，我是那位apa战队的humor，我想说一下这个exe可能出现的问题
![snipaste_2018-06-09_20-10-51](https://user-images.githubusercontent.com/38378287/41191382-4801df0a-6c21-11e8-8267-8fdd32cffa6f.png)
![snipaste_2018-06-09_20-10-28](https://user-images.githubusercontent.com/38378287/41191383-4d36a280-6c21-11e8-85aa-d07ad8fde218.png)
因为你提供的exe没有·ea的签名戳，会不会出现一些问题？

**Comment by lanyizi** [comment]
一般来说不会出现问题吧 毕竟RA3.exe只是个用来启动游戏本体的启动器而已
我觉得唯一的影响是可能会被杀毒软件拦截

**Comment by lanyizi** [comment]
此外数字签名一般是需要证书的，证书好像也是需要购买的
而且无论如何我都不可能有EA的证书，所以也无法给快捷启动器添加EA的数字签名
