### ISSUE TITLE
点击开启控制台的问题

### ISSUE THREAD

**Issue by humor502** [BSG-75/RA3Bar-RA3Launcher#2]
当我用这个exe开启游戏并想点击开启控制台时【在根目录打开】出现了一个提示

我想这可能是因为我的游戏语言导致的---我的语言是法语，，，，，希望增加一些语言的支持
![snipaste_2018-06-09_20-18-51](https://user-images.githubusercontent.com/38378287/41191468-8a893aca-6c22-11e8-92b1-3b3ca30855af.png)

**Comment by lanyizi** [comment]
看上去是字体大小自适应按钮的问题
https://github.com/BSG-75/RA3Bar-RA3Launcher/blob/f6595c6088f48a39f051cb4c6e776308a36b2059/UserInterface.cpp#L740
你5个小时后还在吗，到时候可以QQ私聊了解一下具体情况

**Comment by lanyizi** [comment]
经QQ联系确认，v0.91版已修复这个问题
