### ISSUE TITLE
Upload compiled version to Github Releases?

### ISSUE THREAD

**Issue by AlJohri** [BSG-75/RA3Bar-RA3Launcher#5]
Any chance you can upload the compiled version to Github releases?

**Comment by lanyizi** [comment]
Hi, when years ago I compiled and distributed the executable, I wasn't familiar with Github yet so I didn't upload it to Github releases. Instead you can find it here: https://www.gamereplays.org/community/index.php?showtopic=1013524

If I'm going to make any updates in the future, then yes I'll upload future compiled version to Github releases.

**Comment by AlJohri** [comment]
Thanks! Uploading a copy of the zip here on Github for posterity:
[RA3QuickLoader_v0.91.zip](https://github.com/BSG-75/RA3Bar-RA3Launcher/files/5726725/RA3QuickLoader_v0.91.zip)

**Comment by lanyizi** [comment]
https://github.com/lanyizi/RA3Bar-RA3Launcher/releases/tag/v0.92
